propose:
  description: >
    You are proposing the motion: {motion}
    Come up with a clear argument in favor of motion.
    Be very convincing.
  expected_output: >
    Your clear argument in favor of the motion, in a concise manner.
  agent: debater
  output_files: output/propose.md

oppose:
  description: >
    You are in opposition to the motion: {motion}
    Come up with a clear argument in favor of motion.
    Be very convincing.
  expected_output: >
    Your clear argument in favor of the motion, in a concise manner.
  agent: debater
  output_files: output/oppose.md

decide:
  description: >
    Review the arguments presented by the debaters and decide which side is more convincing.
  expected_output: >
    Your decision which side is more convincing,and why.
  agent: judge
  output_files: output/decide.md
